allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
patchedDependencies:
  '@parcel/workers@2.16.4': patches/@parcel__workers@2.16.4.patch
